#!/data/xsh723/anaconda/bin/python3.6
import edlib


minus = "GTAGGAGGATAGGCGAGTAAATAGGTAGGTAGGTGGATAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGAGGATAGGAGAGTAAATAGGTAGGTAGGTGGATAGGTGGGTAGGTAGGTAGGAGGATAGGAGAGTAAATAGGTAGGTAGGTGGATAGGTAAGGAGGTAGGTAGGAGGAGAGTAAATAGGTAGGTAGGTGGATAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGTAGGAGGACAGGAGAGTAAATAGGTAGGTAGGTGGATAGGTGGGTAGGTAGGTAGGAGGATAGGAGAGTAAATAGGTAGGTAGGTGGATCAGTGGGTAGGTAGGTAGGAGAATAGGAGAGTAAATAGGTAGGTAGGTGGATAGGCAGG"
plus = "CATCCTCCTATCCGCTCATTTATCCATCCATCCACCTATCCATCCATCCATCCATCCATCCATCCATCCATCCATCCTCCTATCCTCTCATTTATCCATCCATCCACCTATCCACCCATCCATCCATCCTCCTATCCTCTCATTTATCCATCCATCCACCTATCCATTCCTCCATCCATCCTCCTCTCATTTATCCATCCATCCACCTATCCATCCATCCATCCATCCATCCATCCATCCATCCATCCATCCATCCTCCTGTCCTCTCATTTATCCATCCATCCACCTATCCACCCATCCATCCATCCTCCTATCCTCTCATTTATCCATCCATCCACCTAGTCACCCATCCATCCATCCTCTTATCCTCTCATTTATCCATCCATCCACCTATCCGTCC"
seq = "CC"



n_hits = 10
hits = 0
top_hits = {}



while hits < n_hits:


    print(minus)
    print(seq)

    alignment = edlib.align(seq, minus, mode='HW', task='path')

    print(alignment)

    for location in alignment['locations']:
        mask_bases = 'X' * (location[1] - location[0])

        minus = minus[:location[0]] + mask_bases + minus[location[1]:]

        hits += 1

        top_hits[hits] = (location, alignment['cigar'])


